version: 2
project_name: orca
builds:
  - main: .
    binary: orca
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format_overrides:
      - goos: windows
        format: zip
brews:
  - name: orca-tui
    repository:
      owner: r7sqtr
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/r7sqtr/orca
    description: Docker Compose TUI manager
